include:
  - ../infraestructure/loki.yml
  - ../infraestructure/promtail.yml
services:
  grafana:
    image: grafana/grafana:latest
    container_name: app-grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ../../_configs/grafana-provision.yml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.http.routers.grafana.entrypoints=web
volumes:
  grafana_data:
