include:
  - ../infraestructure/loki.yml
  - ../infraestructure/promtail.yml
services:
  grafana:
    image: grafana/grafana:12.1.0
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: ${GF_DB_HOST}
      GF_DATABASE_NAME: ${GF_DB_NAME}
      GF_DATABASE_USER: ${GF_DB_USER}
      GF_DATABASE_PASSWORD: ${GF_DB_PASSWORD}
      GF_DATABASE_SSL_MODE: 'disable'
      SCOPE_ORG_ID: ${ENV}
    container_name: app-grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ../../_configs/grafana-provision.yml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.http.routers.grafana.entrypoints=web
volumes:
  grafana_data:
