include:
  - ../infraestructure/loki.yml
  - ../infraestructure/promtail.yml
services:
  grafana:
    extends:
      file: ./environment/${ENV}.yml
      service: grafana
    image: grafana/grafana:12.1.0
    environment:
      GF_SERVER_DOMAIN: grafana.${DOMAIN}
      GF_SERVER_ROOT_URL: ${PROTOCOL}://grafana.${DOMAIN}
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: ${GF_DB_HOST}
      GF_DATABASE_NAME: ${GF_DB_NAME}
      GF_DATABASE_USER: ${GF_DB_USER}
      GF_DATABASE_PASSWORD: ${GF_DB_PASSWORD}
      GF_DATABASE_SSL_MODE: 'disable'
      SCOPE_ORG_ID: ${ENV}
    container_name: app-grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ../../_configs/grafana-provision.yml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
    profiles:
      - all
      - app
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.http.routers.grafana.middlewares=grafana-cors
      - traefik.http.middlewares.grafana-cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST
      - traefik.http.middlewares.grafana-cors.headers.accesscontrolalloworiginlist=${PROTOCOL}://${DOMAIN}
      - traefik.http.middlewares.grafana-cors.headers.accesscontrolmaxage=100
      - traefik.http.middlewares.grafana-cors.headers.addvaryheader=true
      - traefik.http.middlewares.grafana-cors.headers.accesscontrolallowcredentials=true
  superset:
    extends:
      file: ./environment/${ENV}.yml
      service: superset
    image: apache/superset:5.0.0-dev
    container_name: app-superset
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - POSTGRES_USER=${SS_DB_USER}
      - POSTGRES_PASSWORD=${SS_DB_PASSWORD}
      - POSTGRES_DB=${SS_DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - SUPERSET_SECRET_KEY=uvwvNnQBIyfwglGQPYXJYGmRQpFgQkvx
      - ADMIN_USERNAME=admin
      - ADMIN_FIRSTNAME=Superset
      - ADMIN_LASTNAME=Admin
      - ADMIN_EMAIL=admin@sespesoft.com
      - ADMIN_PASSWORD=Qazwsx*
      - PYTHONPATH=/app/superset
    profiles:
      - all
      - app
    restart: unless-stopped
    volumes:
      - superset_data:/app/superset_home
      - ../../_configs/superset_entrypoint.sh:/app/superset_entrypoint.sh
      - ../../_configs/superset_config.py:/app/superset/superset_config.py
    entrypoint: [/app/superset_entrypoint.sh]
    labels:
      - traefik.enable=true
      - traefik.http.routers.superset.rule=Host(`superset.${DOMAIN}`)
      - traefik.http.services.superset.loadbalancer.server.port=8088
      - traefik.http.routers.superset.middlewares=superset-cors
      - traefik.http.middlewares.superset-cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST
      - traefik.http.middlewares.superset-cors.headers.accesscontrolalloworiginlist=${PROTOCOL}://${DOMAIN}
      - traefik.http.middlewares.superset-cors.headers.accesscontrolmaxage=100
      - traefik.http.middlewares.superset-cors.headers.addvaryheader=true
      - traefik.http.middlewares.superset-cors.headers.accesscontrolallowcredentials=true
volumes:
  grafana_data:
  superset_data:
