services:
  pgadmin:
    container_name: app-pgadmin
    image: dpage/pgadmin4
    ports:
      - 127.0.0.1:8084:80
    user: ${UID}:${GID}
    volumes:
      - ./storage:/var/lib/pgadmin/storage
    environment:
      - PGADMIN_CONFIG_WTF_CSRF_CHECK_DEFAULT=False
      - PGADMIN_DEFAULT_EMAIL=admin@sespesoft.com
      - PGADMIN_DEFAULT_PASSWORD=Qazwsx*
    profiles:
      - all
      - app
    restart: unless-stopped
