include:
  - _services/infraestructure/traefik.yml
  - _services/infraestructure/database.yml
  - _services/infraestructure/minio.yml
  - _services/infraestructure/rabbitmq.yml
  - _services/infraestructure/redis.yml
  - _services/application/grafana.yml
  - _services/application/grafana-bi.yml
  #- _services/application/superset.yml
  - _services/application/jasper.yml
  - _services/application/pgadmin.yml
  - _services/application/n8n.yml
  - _services/domain/auth.yml
  - _services/domain/notify.yml
  - _services/domain/pqrs.yml
  - _services/domain/hiring.yml
  - _services/domain/pgaudit.yml
  - _services/domain/geo.yml
  - _services/domain/audit.yml
services:
  webapp:
    extends:
      file: ./_services/domain/environment/${ENV}.yml
      service: webapp
    profiles:
      - all
      - app
    labels:
      - traefik.enable=true
      - traefik.http.services.webapp.loadbalancer.server.port=80
      - traefik.http.routers.webapp.rule=Host(`${DOMAIN}`)
secrets:
  priv_key:
    file: ./_configs/priv.key
configs:
  pub_key:
    file: ./_configs/pub.key
