x-config-srv: &config-srv
  restart: unless-stopped
x-config-job: &config-job
  restart: on-failure
  depends_on:
    db:
      condition: service_healthy
    rabbitmq:
      condition: service_healthy
services:
  webapp:
    build:
      context: ../../../webapp
      additional_contexts:
        - assets=../../../_assets
    labels:
      - traefik.http.routers.webapp.entrypoints=web
    <<: *config-srv
  audit:
    build:
      context: ../../../audit
    labels:
      - traefik.http.routers.audit.entrypoints=web
    depends_on:
      job_audit:
        condition: service_completed_successfully
    <<: *config-srv
  job_audit:
    build:
      context: ../../../audit
    <<: *config-job
  auth:
    build:
      context: ../../../auth
    labels:
      - traefik.http.routers.auth.entrypoints=web
    depends_on:
      job_auth:
        condition: service_completed_successfully
    <<: *config-srv
  job_auth:
    build:
      context: ../../../auth
    <<: *config-job
  geo:
    build:
      context: ../../../geo
    labels:
      - traefik.http.routers.geo.entrypoints=web
    depends_on:
      job_geo:
        condition: service_completed_successfully
    <<: *config-srv
  job_geo:
    build:
      context: ../../../geo
    <<: *config-job
  hiring:
    build:
      context: ../../../hiring
    labels:
      - traefik.http.routers.hiring.entrypoints=web
    depends_on:
      job_hiring:
        condition: service_completed_successfully
    <<: *config-srv
  job_hiring:
    build:
      context: ../../../hiring
    <<: *config-job
  pgaudit:
    build:
      context: ../../../pgaudit-api
    labels:
      - traefik.http.routers.pga.entrypoints=web
    depends_on:
      job_pgaudit:
        condition: service_completed_successfully
    <<: *config-srv
  job_pgaudit:
    build:
      context: ../../../pgaudit-api
    <<: *config-job
  pqrs:
    build:
      context: ../../../pqrs
    labels:
      - traefik.http.routers.pqr.entrypoints=web
    depends_on:
      job_pqrs:
        condition: service_completed_successfully
    <<: *config-srv
  job_pqrs:
    build:
      context: ../../../pqrs
    <<: *config-job
  notify:
    build:
      context: ../../../notify-soketi
    labels:
      - traefik.http.routers.notify.entrypoints=web
    depends_on:
      soketi:
        condition: service_started
    <<: *config-srv
  soketi:
    environment:
      SOKETI_DEBUG: true
    labels:
      - traefik.http.routers.soketi.entrypoints=web
    depends_on:
      redis:
        condition: service_healthy
    <<: *config-srv
