x-deploy-srv: &deploy-srv
  replicas: 1
  update_config:
    parallelism: 1
    order: start-first
    failure_action: rollback
    delay: 10s
x-config-srv: &config-srv
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 40s
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
x-config-job: &config-job
  deploy:
    mode: replicated-job
    replicas: 1
    restart_policy:
      condition: on-failure
      delay: 15s
      max_attempts: 5
      window: 120s
services:
  webapp:
    image: ${WEBAPP_IMAGE}
    <<: *config-srv
    labels: &webapp-tls-labels
      - traefik.http.routers.webapp.tls=true
      - traefik.http.middlewares.rate-limit.ratelimit.average=300
      - traefik.http.middlewares.rate-limit.ratelimit.burst=50
      - traefik.http.middlewares.rate-limit.ratelimit.period=1m
      - traefik.http.routers.webapp.middlewares=rate-limit
    deploy:
      <<: *deploy-srv
      labels: *webapp-tls-labels
  audit:
    image: ${AUDIT_IMAGE}
    <<: *config-srv
    labels: &audit-tls-labels
      - traefik.http.routers.audit.tls=true
      - traefik.http.routers.audit.middlewares=rate-limit
    deploy:
      <<: *deploy-srv
      labels: *audit-tls-labels
  job_audit:
    image: ${AUDIT_IMAGE}
    <<: *config-job
  auth:
    image: ${AUTH_IMAGE}
    <<: 
    <<: *config-srv
    labels: &auth-tls-labels
      - traefik.http.routers.auth.tls=true
      - traefik.http.routers.auth.middlewares=rate-limit
    deploy:
      <<: *deploy-srv
      labels: *auth-tls-labels
  job_auth:
    image: ${AUTH_IMAGE}
    <<: *config-job
  geo:
    image: ${CONF_IMAGE}
    <<: *config-srv
    labels: &geo-tls-labels
      - traefik.http.routers.geo.tls=true
      - traefik.http.routers.geo.middlewares=rate-limit
    deploy:
      <<: *deploy-srv
      labels: *geo-tls-labels
  job_geo:
    image: ${CONF_IMAGE}
    <<: *config-job
  hiring:
    image: ${HIRING_IMAGE}
    <<: *config-srv
    labels: &hring-tls-labels
      - traefik.http.routers.hiring.tls=true
      - traefik.http.routers.hiring.middlewares=rate-limit
    deploy:
      <<: *deploy-srv
      labels: *hiring-tls-labels
  job_hiring:
    image: ${HIRING_IMAGE}
    <<: *config-job
  pgaudit:
    image: ${PGAUDIT_IMAGE}
    <<: *config-srv
    labels: &pga-tls-labels
      - traefik.http.routers.pga.tls=true
      - traefik.http.routers.pga.middlewares=rate-limit
    deploy:
      <<: *deploy-srv
      labels: *pga-tls-labels
  job_pgaudit:
    image: ${PGAUDIT_IMAGE}
    <<: *config-job
  pqrs:
    image: ${PQRS_IMAGE}
    <<: *config-srv
    labels: &pqrs-tls-labels
      - traefik.http.routers.pqr.tls=true
      - traefik.http.routers.pqr.middlewares=rate-limit
    deploy:
      <<: *deploy-srv
      labels: *pqrs-tls-labels
  job_pqrs:
    image: ${PQRS_IMAGE}
    <<: *config-job
  notify:
    image: ${NOTIFY_IMAGE}
    environment:
      APP_ENV: production
      APP_DEBUG: false
    <<: *config-srv
    labels: &notify-tls-labels
      - traefik.http.routers.notify.tls=true
      - traefik.http.routers.notify.middlewares=rate-limit
    deploy:
      <<: *deploy-srv
      labels: *notify-tls-labels
  soketi:
    <<: *config-srv
    labels: &soketi-tls-labels
      - traefik.http.routers.soketi.tls=true
      - traefik.http.middlewares.soketi-rate-limit.ratelimit.average=100
      - traefik.http.middlewares.soketi-rate-limit.ratelimit.burst=200
      - traefik.http.middlewares.soketi-rate-limit.ratelimit.period=1m
      - traefik.http.routers.soketi.middlewares=soketi-rate-limit
    deploy:
      <<: *deploy-srv
      labels: *soketi-tls-labels
  job_notify:
    image: ${NOTIFY_IMAGE}
    <<: *config-job
