x-deploy-srv: &deploy-srv
  replicas: 1
  update_config:
    parallelism: 1
    order: start-first
    failure_action: rollback
    delay: 10s
x-healthcheck-srv: &healthcheck-srv
  test: ["CMD", "curl", "-f", "http://localhost"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 40s
x-config-job: &config-job
  deploy:
    mode: replicated
    replicas: 1
    restart_policy:
      condition: on-failure
      delay: 15s
      max_attempts: 5
      window: 120s
services:
  webapp:
    image: ${WEBAPP_IMAGE}
    healthcheck: *healthcheck-srv
    deploy:
      <<: *deploy-srv
      labels:
        - traefik.http.routers.webapp.entrypoints=websecure
        - traefik.http.routers.webapp.tls=true
        - traefik.http.routers.webapp.tls.certresolver=le
        - traefik.http.middlewares.rate-limit.ratelimit.average=300
        - traefik.http.middlewares.rate-limit.ratelimit.burst=50
        - traefik.http.middlewares.rate-limit.ratelimit.period=1m
        - traefik.http.routers.webapp.middlewares=rate-limit
  audit:
    image: ${AUDIT_IMAGE}
    healthcheck: *healthcheck-srv
    deploy:
      <<: *deploy-srv
      labels:
        - traefik.http.routers.audit.entrypoints=websecure
        - traefik.http.routers.audit.tls=true
        - traefik.http.routers.audit.tls.certresolver=le
        - traefik.http.routers.audit.middlewares=rate-limit
  job_audit:
    image: ${AUDIT_IMAGE}
    <<: *config-job
  auth:
    image: ${AUTH_IMAGE}
    <<: 
    healthcheck: *healthcheck-srv
    deploy:
      <<: *deploy-srv
      labels:
        - traefik.http.routers.auth.entrypoints=websecure
        - traefik.http.routers.auth.tls=true
        - traefik.http.routers.auth.tls.certresolver=le
        - traefik.http.routers.auth.middlewares=rate-limit
  job_auth:
    image: ${AUTH_IMAGE}
    <<: *config-job
  geo:
    image: ${CONF_IMAGE}
    healthcheck: *healthcheck-srv
    deploy:
      <<: *deploy-srv
      labels:
        - traefik.http.routers.geo.entrypoints=websecure
        - traefik.http.routers.geo.tls=true
        - traefik.http.routers.geo.tls.certresolver=le
        - traefik.http.routers.geo.middlewares=rate-limit
  job_geo:
    image: ${CONF_IMAGE}
    <<: *config-job
  hiring:
    image: ${HIRING_IMAGE}
    healthcheck: *healthcheck-srv
    deploy:
      <<: *deploy-srv
      labels:
        - traefik.http.routers.hiring.entrypoints=websecure
        - traefik.http.routers.hiring.tls=true
        - traefik.http.routers.hiring.tls.certresolver=le
        - traefik.http.routers.hiring.middlewares=rate-limit
  job_hiring:
    image: ${HIRING_IMAGE}
    <<: *config-job
  pgaudit:
    image: ${PGAUDIT_IMAGE}
    healthcheck: *healthcheck-srv
    deploy:
      <<: *deploy-srv
      labels:
        - traefik.http.routers.pga.entrypoints=websecure
        - traefik.http.routers.pga.tls=true
        - traefik.http.routers.pga.tls.certresolver=le
        - traefik.http.routers.pga.middlewares=rate-limit
  job_pgaudit:
    image: ${PGAUDIT_IMAGE}
    <<: *config-job
  pqrs:
    image: ${PQRS_IMAGE}
    healthcheck: *healthcheck-srv
    deploy:
      <<: *deploy-srv
      labels:
        - traefik.http.routers.pqr.entrypoints=websecure
        - traefik.http.routers.pqr.tls=true
        - traefik.http.routers.pqr.tls.certresolver=le
        - traefik.http.routers.pqr.middlewares=rate-limit
  job_pqrs:
    image: ${PQRS_IMAGE}
    <<: *config-job
  notify:
    image: ${NOTIFY_IMAGE}
    environment:
      APP_ENV: production
      APP_DEBUG: false
    healthcheck: *healthcheck-srv
    deploy:
      <<: *deploy-srv
      labels:
        - traefik.http.routers.notify.entrypoints=websecure
        - traefik.http.routers.notify.tls=true
        - traefik.http.routers.notify.tls.certresolver=le
        - traefik.http.routers.notify.middlewares=rate-limit
  soketi:
    healthcheck: *healthcheck-srv
    deploy:
      <<: *deploy-srv
      labels:
        - traefik.http.routers.soketi.entrypoints=websecure
        - traefik.http.routers.soketi.tls=true
        - traefik.http.routers.soketi.tls.certresolver=le
        - traefik.http.middlewares.soketi-rate-limit.ratelimit.average=100
        - traefik.http.middlewares.soketi-rate-limit.ratelimit.burst=200
        - traefik.http.middlewares.soketi-rate-limit.ratelimit.period=1m
        - traefik.http.routers.soketi.middlewares=soketi-rate-limit
  job_notify:
    image: ${NOTIFY_IMAGE}
    <<: *config-job
