x-deploy-srv: &deploy-srv
  replicas: 1
  update_config:
    parallelism: 1
    order: start-first
    failure_action: rollback
    delay: 10s
x-healthcheck-srv: &healthcheck-srv
  test: ["CMD", "curl", "-f", "http://localhost"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 40s
x-config-job: &config-job
  deploy:
    mode: replicated-job
    replicas: 1
    restart_policy:
      condition: on-failure
      delay: 15s
      max_attempts: 5
      window: 120s
services:
  webapp:
    image: ${WEBAPP_IMAGE}
    healthcheck: *healthcheck-srv
    labels: &webapp-tls-labels
      - traefik.http.routers.webapp.tls=true
    deploy:
      <<: *deploy-srv
      labels: *webapp-tls-labels
  audit:
    image: ${AUDIT_IMAGE}
    healthcheck: *healthcheck-srv
    labels: &audit-tls-labels
      - traefik.http.routers.audit.tls=true
    deploy:
      <<: *deploy-srv
      labels: *audit-tls-labels
  job_audit:
    image: ${AUDIT_IMAGE}
    <<: *config-job
  auth:
    image: ${AUTH_IMAGE}
    healthcheck: *healthcheck-srv
    labels: &auth-tls-labels
      - traefik.http.routers.auth.tls=true
    deploy:
      <<: *deploy-srv
      labels: *auth-tls-labels
  job_auth:
    image: ${AUTH_IMAGE}
    <<: *config-job
  geo:
    image: ${CONF_IMAGE}
    healthcheck: *healthcheck-srv
    labels: &geo-tls-labels
      - traefik.http.routers.geo.tls=true
    deploy:
      <<: *deploy-srv
      labels: *geo-tls-labels
  job_geo:
    image: ${CONF_IMAGE}
    <<: *config-job
  hiring:
    image: ${HIRING_IMAGE}
    healthcheck: *healthcheck-srv
    labels: &hiring-tls-labels
      - traefik.http.routers.hiring.tls=true
    deploy:
      <<: *deploy-srv
      labels: *hiring-tls-labels
  job_hiring:
    image: ${HIRING_IMAGE}
    <<: *config-job
  pgaudit:
    image: ${PGAUDIT_IMAGE}
    healthcheck: *healthcheck-srv
    labels: &pga-tls-labels
      - traefik.http.routers.pga.tls=true
    deploy:
      <<: *deploy-srv
      labels: *pga-tls-labels
  job_pgaudit:
    image: ${PGAUDIT_IMAGE}
    <<: *config-job
  pqrs:
    image: ${PQRS_IMAGE}
    healthcheck: *healthcheck-srv
    labels: &pqrs-tls-labels
      - traefik.http.routers.pqr.tls=true
    deploy:
      <<: *deploy-srv
      labels: *pqrs-tls-labels
  job_pqrs:
    image: ${PQRS_IMAGE}
    <<: *config-job
  notify:
    image: ${NOTIFY_IMAGE}
    environment:
      APP_ENV: production
      APP_DEBUG: false
    healthcheck: *healthcheck-srv
    labels: &notify-tls-labels
      - traefik.http.routers.notify.tls=true
    deploy:
      <<: *deploy-srv
      labels: *notify-tls-labels
  soketi:
    healthcheck: *healthcheck-srv
    labels: &soketi-tls-labels
      - traefik.http.routers.soketi.tls=true
    deploy:
      <<: *deploy-srv
      labels: *soketi-tls-labels
  job_notify:
    image: ${NOTIFY_IMAGE}
    <<: *config-job
