x-deploy-app: &deploy-app
  mode: replicated
  replicas: 1
  placement:
    constraints:
      - node.role == manager
services:
  grafana:
    labels: &grafana-tls-labels
      - traefik.http.routers.grafana.tls=true
    deploy:
      <<: *deploy-app
      labels: *grafana-tls-labels
  superset:
    labels: &superset-tls-labels
      - traefik.http.routers.superset.tls=true
    deploy:
      <<: *deploy-app
      labels: *superset-tls-labels
  jasper:
    labels: &jasper-tls-labels
      - traefik.http.routers.bi.tls=true
    deploy:
      <<: *deploy-app
      labels: *jasper-tls-labels
  n8n:
    labels: &n8n-tls-labels
      - traefik.http.routers.n8n.tls=true
    deploy:
      <<: *deploy-app
      labels: *n8n-tls-labels
