services:
  db:
    container_name: infra-db
    image: postgres:14.1-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../../_configs/db-provision.sh:/docker-entrypoint-initdb.d/db-provision.sh
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      APP_DB_NAME: ${DB_NAME}
      APP_DB_USER: ${DB_USER}
      APP_DB_PASSWORD: ${DB_PASSWORD}
      BI_DB_NAME: ${BI_DB_NAME}
      BI_DB_USER: ${BI_DB_USER}
      BI_DB_PASSWORD: ${BI_DB_PASSWORD}
      GF_DB_NAME: ${GF_DB_NAME}
      GF_DB_USER: ${GF_DB_USER}
      GF_DB_PASSWORD: ${GF_DB_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: [CMD-SHELL, "pg_isready --username=${DB_USER} --dbname=${DB_NAME}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    profiles:
      - all
      - infra
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role == manager
volumes:
  pg_data:
