services:
  promtail:
    image: grafana/promtail:3.5.3
    container_name: infra-promtail
    environment:
      - SCOPE_ORG_ID=${ENV}
    volumes:
      - ${PROMTAIL_POSITION_PATH}:/promtail
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../../_configs/promtail.yml:/etc/promtail/config.yml:ro
    command:
      - -config.file=/etc/promtail/config.yml
      - -config.expand-env=true
    restart: unless-stopped
    profiles:
      - all
      - infra
    deploy:
      mode: global
