services:
  promtail:
    image: grafana/promtail:2.9.0
    container_name: infra-promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../../_configs/promtail.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    deploy:
      mode: global
