services:
  traefik:
    image: traefik:v3.0
    container_name: infra-traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    profiles:
      - all
      - app
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role == manager
